logoText: Elias Peeters
logoType: "short" # long, short
description: "Homepage of Elias Peeters"
custom_css: ["scss/custom.css"]
custom_js: []
useFaviconGenerator: true # https://www.favicon-generator.org/
meta_image: ""
themecolor: ""

themeOptions: ["light", "kimbie"]
notAllowedTypesInHome: ["contact", "talks", "about", "projects", "publication", "presentation", "resume", "calendar"]
notAllowedTypesInHomeSidebar: ["about", "archive", "projects", "publication", "presentation", "resume", "calendar"]
notAllowedTypesInArchive: ["about", "contact", "talks", "projects", "publication", "presentation", "resume", "calendar"]
notAllowedTypesInHomeFeed: ["about", "archive", "contact", "talks", "projects", "publication", "presentation", "resume", "gallery", "calendar"]

viewportSize: "normal" # widest, wider, wide, normal, narrow
enableUiAnimation: true
hideSingleContentsWhenJSDisabled: false
enablePinnedPosts: true
minItemsToShowInTagCloud: 1 # Minimum items to show in tag cloud

# header
homeHeaderType: "text" # text, img, slide

# menu
showMobileMenuTerms: ["tags", "categories", "series"]

# body
enableBreadcrumb: true
enablePhotoSwipe: true
enableSearch: true
enableSearchHighlight: true
enableGoToTop: true
enableWhoami: true
summaryShape: "classic" # card, classic, compact
searchResultPosition: "main" # side, main
archiveGroupByDate: "2006" # "2006-01": group by month, "2006": group by year
archivePaginate: 13
paginateWindow: 1
talksPaginate: 5
talksGroupByDate: "2006"
pubPaginate: 20

# whoami
myname: "Elias Peeters"
email: "elias.peeters@icloud.com"
whoami: "üñ• Worlds best developer since 2001"
bioImageUrl: ""
useGravatar: false
location: "Germany, Geesthacht"
organization: "otto.de"
link: "https://eliaspeeters.de"

# sidebar
enableBio: true
enableBioImage: true
enableSidebar: true
enableSidebarTags: true
enableSidebarSeries: true
enableSidebarCategories: true
enableHomeSidebarTitles: true
enableListSidebarTitles: true
enableToc: true
hideToc: false
tocFolding: true
tocPosition: "inner" # inner, outer
enableTocSwitch: true
itemsPerCategory: 5
sidebarPosition: "right"
tocLevels: ["h2", "h3", "h4"]
enableSidebarPostsByOrder: false

# footer
showPoweredBy: true
showFeedLinks: true
showSocialLinks: true
enableLangChange: false
enableThemeChange: false

# service
googleTagManager: "" # GTM-XXXXXX
baiduAnalytics: ""
enableBusuanzi: false
busuanziSiteUV: true
busuanziSitePV: true
busuanziPagePV: true

# rss
updatePeriod: "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency: ""
fullContents: false

# comment
enableComment: false
disqus_shortname: ""
commento: false

telegram:
  enable: false
  siteId: ""
  dataLimit: 5

gitment:          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner: ""              # Your GitHub ID
  repo: ""               # The repo to store comments
  clientId: ""           # Your client ID
  clientSecret: ""       # Your client secret

utterances:       # https://utteranc.es/
  owner: ""              # Your GitHub ID
  repo: ""               # The repo to store comments

gitalk:           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner: ""              # Your GitHub ID
  repo: ""               # The repo to store comments
  clientId: ""           # Your client ID
  clientSecret: ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
valine:
  enable: false
  appId: ""
  appKey: ""
  notify: false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  avatar: 'mm'
  placeholder: 'ËØ¥ÁÇπ‰ªÄ‰πàÂêß...'
  visitor: false

changyan:
  changyanAppid: ""        # Changyan app id             # ÁïÖË®Ä
  changyanAppkey: ""       # Changyan app key

livere:
  livereUID: ""            # LiveRe UID                  # Êù•ÂøÖÂäõ

# Isso: https://posativ.org/isso/
isso:
  enable: false
  scriptSrc: "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs: "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

socialOptions:
  email: "mailto:elias.peeters@icloud.com"
  phone: "tel:+491723445175"
  facebook: ""
  twitter: "https://twitter.com/elias_peeters"
  github: "https://github.com/EliasPeeters"
  stack-overflow: ""
  instagram: ""
  google-plus: ""
  youtube: ""
  medium: ""
  tumblr: ""
  linkedin: "https://www.linkedin.com/in/elias-peeters-2014641b4"
  pinterest: ""
  stack-exchange: ""
  telegram: "https://t.me/EliasPeeters"
  steam: ""
  weibo: ""
  douban: ""
  csdn: ""
  gitlab: ""
  mastodon: ""
  jianshu: ""
  zhihu: ""
  signal: ""
  whatsapp: "https://wa.me/491723445175"
  matrix: ""
  xmpp: ""
  dev-to: ""
  gitea: ""
  google-scholar: ""
  orcid: ""
  xing: ""
  keybase: ""
  applemusic: ""

donationOptions:
  enable: false
  alipay: ""
  wechat: ""
  paypal: ""
  patreon: ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
share:
  - name: "facebook"
    username: ""
  - name: "twitter"

footerLinks:
  - name: "Privacy Policy"
    link: "/privacy/"
  - name: "Imprint"
    link: "/imprint/"
